package edu.uwm.cs.pir

trait Base {
  
  // contract between pipeline and MIR domain functions
  
  type ID 																			// Index is generated by the pipeline semantics while it is abstract to domain functions
  type FeatureDoc[X]		 	= (ID, X)											// feature document consists of an ID and a feature (set)
  
  type CpsOp[X, Y, C]			= (X, Y) => C										// composition operator
  
  type OdrOp[X]					= (FeatureDoc[X], FeatureDoc[X]) => Boolean			// ordering operator
  type FltOp[X, L]				= List[FeatureDoc[L]] => FeatureDoc[X] => Boolean	// filtering operator
  
  type Dir[X]					= List[X]											// file directory type
  type LoadOp[P, X]				= P => X											// loading operator
  
  type PrjOp[X, Y] 				= X => Y											// projection operator
  type DPrjOp[X, Y, D] 			= (X, D) => Y										// dependent projection operator
  
  type IdxOp[X, I] 				= List[FeatureDoc[X]] => I							// indexing operator
    
  type TrnOp[X, M] 				= List[FeatureDoc[X]] => M							// training operator
//  type TrnOp2[X, Y, M]			= (List[FeatureDoc[X]], List[FeatureDoc[Y]]) => M	// cross correlation training operator
}